/* ============================================================
   GYNECO-QUEST — Base de données des questions
   Source : "Réponses aux questions gynéco Chu-YO" + "Gyneco-hyper"
   Chaque carte : { id, cat, q (question), a (réponse), mnemo?, diff(1-3) }
   ============================================================ */
window.GYNECO = {
  categories: [
    { id: "defs",   name: "Définitions clés",            emoji: "📖", color: "#6366f1", blurb: "Les définitions qui tombent tout le temps." },
    { id: "acc",    name: "Accouchement & mécanique",     emoji: "🤰", color: "#ec4899", blurb: "Périodes, contractions, engagement, repères." },
    { id: "presD",  name: "Présentations dystociques",    emoji: "🔄", color: "#f59e0b", blurb: "Siège, face, front, épaule." },
    { id: "urg",    name: "Urgences hémorragiques",       emoji: "🩸", color: "#ef4444", blurb: "HRP, PP, hémorragie délivrance, rupture utérine, GEU." },
    { id: "pe",     name: "Pré-éclampsie / HTA",          emoji: "⚡", color: "#eab308", blurb: "Pré-éclampsie, HELLP, éclampsie, sulfate de Mg." },
    { id: "pp",     name: "Post-partum & suites",         emoji: "🍼", color: "#14b8a6", blurb: "Endométrite, GATPA, surveillance, conseils." },
    { id: "avort",  name: "Avortement & SAA",             emoji: "💔", color: "#a855f7", blurb: "Avortement, complications, soins après avortement." },
    { id: "cesar",  name: "Césarienne & gestes",          emoji: "🔪", color: "#3b82f6", blurb: "Définitions, indications, boîte, DA/RU." },
    { id: "infect", name: "Infections / RPM / Palu / VIH", emoji: "🦠", color: "#84cc16", blurb: "RPM, infections, paludisme, PTME." },
    { id: "contra", name: "Contraception & PF",           emoji: "💊", color: "#06b6d4", blurb: "Contraception d'urgence, MAMA, indications." },
    { id: "onco",   name: "Cancers & tumeurs",            emoji: "🎗️", color: "#f43f5e", blurb: "Col, sein, kystes, fibromes, môle." },
    { id: "gyn",    name: "Gynéco médicale",              emoji: "🌸", color: "#d946ef", blurb: "Cycle, aménorrhée, puberté, infertilité, GEU." },
    { id: "sp",     name: "Santé publique / SONU",        emoji: "🏥", color: "#0ea5e9", blurb: "SONU, 3 retards, mortalité maternelle, CPN." },
    { id: "terr",   name: "Terrains particuliers",        emoji: "🧬", color: "#f97316", blurb: "Drépano, anémie, diabète, vomissements." }
  ],

  cards: [
    /* ---------------- DÉFINITIONS CLÉS ---------------- */
    { id:"d1", cat:"defs", diff:1, q:"Définir la césarienne",
      a:"Intervention chirurgicale qui consiste en l'incision de l'abdomen et de l'utérus d'une femme afin d'extraire le fœtus hors de l'utérus." },
    { id:"d2", cat:"defs", diff:2, q:"Définir l'accouchement",
      a:"Ensemble des phénomènes physiologiques qui aboutissent à l'expulsion du fœtus et de ses annexes hors des voies génitales, à partir du moment où l'âge théorique de la grossesse est ≥ 28 SA." },
    { id:"d3", cat:"defs", diff:1, q:"Définir l'accouchement à terme (bornes en jours)",
      a:"Entre le début de la 37ᵉ semaine (259 jours) et la fin de la 41ᵉ semaine (287 jours) d'aménorrhée.", mnemo:"259 → 287 jours" },
    { id:"d4", cat:"defs", diff:2, q:"Définir la prééclampsie",
      a:"Association d'une HTA à une protéinurie au cours de la grossesse, après 20 SA." },
    { id:"d5", cat:"defs", diff:2, q:"Définir le placenta prævia + 2 complications",
      a:"Insertion partielle ou totale du placenta sur le segment inférieur.\nComplications : accouchement prématuré, procidence du cordon, hémorragie, RPM." },
    { id:"d6", cat:"defs", diff:2, q:"Définir l'épisiotomie + complications",
      a:"Incision chirurgicale du périnée réalisée lors de l'accouchement pour faciliter le passage du bébé et prévenir les déchirures graves.\nComplications : hémorragie, infection de la plaie, douleurs/inconfort prolongé." },
    { id:"d7", cat:"defs", diff:2, q:"Définir hystérectomie totale, subtotale, annexectomie",
      a:"• Totale : ablation complète de l'utérus, col inclus\n• Subtotale : ablation du corps utérin en laissant le col\n• Annexectomie : ablation des annexes (trompes + ovaires)" },
    { id:"d8", cat:"defs", diff:2, q:"Définir l'endométriose + localisations",
      a:"Présence de tissu endométrial (glandes + stroma) en dehors de la cavité utérine.\n• Pelviennes : ovaire (endométriome), ligaments larges, CDS de Douglas, ligaments utéro-sacrés, péritoine\n• Extra-pelvienne : poumon, rein, ombilic, cicatrice de césarienne" },
    { id:"d9", cat:"defs", diff:1, q:"Définir l'endométriose + 2 signes fonctionnels",
      a:"Maladie chronique gynécologique : tissu endométrial (glandes + stroma) hors de la cavité utérine.\nSF : dysménorrhée intense, dyspareunie profonde." },
    { id:"d10", cat:"defs", diff:1, q:"Définir : DA (délivrance artificielle) et RU (révision utérine)",
      a:"• DA : manœuvre visant à extraire manuellement le placenta lorsqu'il ne se décolle pas spontanément après l'accouchement.\n• RU : exploration manuelle de la cavité utérine pour vérifier l'absence de débris placentaires ou de caillots." },
    { id:"d11", cat:"defs", diff:2, q:"Définir hystérocèle, rectocèle, cystocèle, élytrocèle",
      a:"• Hystérocèle : prolapsus / ptose utérine à divers degrés\n• Rectocèle : hernie de la face antérieure du rectum refoulant en avant/bas la face postérieure du vagin\n• Cystocèle : hernie de la face postérieure de la vessie refoulant en arrière/bas la face antérieure du vagin\n• Élytrocèle : clivage de la cloison recto-vaginale par le cul-de-sac de Douglas" },
    { id:"d12", cat:"defs", diff:2, q:"Définir l'avortement selon l'OMS",
      a:"Expulsion hors des voies génitales du produit de conception avant 22 SA (ou 20 semaines de grossesse), ou d'un fœtus < 500 g lorsque la date des dernières règles n'est pas connue." },
    { id:"d13", cat:"defs", diff:1, q:"Définir la mortalité maternelle",
      a:"Décès d'une femme pendant la grossesse, l'accouchement ou dans les 42 jours qui suivent, quelle que soit la durée/le siège de la grossesse, pour toute cause liée à la grossesse ou à ses soins." },
    { id:"d14", cat:"defs", diff:2, q:"Définir le vomissement gravidique + signes de gravité",
      a:"Rejet par la bouche du contenu de l'estomac au cours de la grossesse (1ᵉʳ trimestre), sans cause organique.\nGravité : AEG/amaigrissement important, pouls > 100, tachypnée, fièvre, oligurie, ictère, torpeur, dénutrition." },
    { id:"d15", cat:"defs", diff:1, q:"Définir l'épreuve du travail",
      a:"Auto-observation de la prise de contact de la présentation avec le détroit supérieur sous l'effet des contractions utérines. Critère de réussite : engagement franc de la tête fœtale." },
    { id:"d16", cat:"defs", diff:1, q:"Définir l'épreuve utérine",
      a:"Travail d'accouchement sur utérus cicatriciel." },
    { id:"d17", cat:"defs", diff:1, q:"Définir l'engagement + son diagnostic",
      a:"Franchissement de l'aire du détroit supérieur par le plus grand diamètre de la présentation.\nDiagnostic : signe de Farabeuf.", mnemo:"Engagement = Farabeuf" },
    { id:"d18", cat:"defs", diff:2, q:"Définir la MAMA",
      a:"Méthode contraceptive utilisant l'allaitement maternel exclusif pendant 4 à 6 mois. Tétées fréquentes (≥10/j, les 2 seins) → blocage de l'ovulation → aménorrhée. Ne pas donner d'eau à l'enfant.", mnemo:"Allaitement Maternel + Aménorrhée" },
    { id:"d19", cat:"defs", diff:1, q:"Définir la technique IVA / IVL",
      a:"Inspection Visuelle du col utérin après application d'Acide acétique (IVA) et de Lugol (IVL)." },
    { id:"d20", cat:"defs", diff:2, q:"Définir le kyste ovarien organique + traitement",
      a:"Processus prolifératif bénin ou borderline à composante liquidienne, taille > 6 mm, croissance non liée à un dysfonctionnement hormonal.\nTRT chirurgical si > 5 cm (kystectomie, ovariectomie, annexectomie, voire hystérectomie + annexectomie si > 50 ans) + anapath. Si < 5 cm : ponction écho-guidée. Enceinte : cœlioscopie avant 16-17 SA, laparotomie au-delà." },
    { id:"d21", cat:"defs", diff:2, q:"Définir la GEU",
      a:"Grossesse extra-utérine (nidation ectopique) : implantation et évolution de la grossesse en dehors de la cavité utérine." },
    { id:"d22", cat:"defs", diff:2, q:"Définir la rupture utérine",
      a:"Solution de continuité de la paroi de l'utérus gravide, due à un facteur fragilisant ou à une tension excessive. Sont exclues les perforations traumatiques et les déchirures du col." },
    { id:"d23", cat:"defs", diff:2, q:"Définir la présentation par le siège",
      a:"Présentation longitudinale dans laquelle l'extrémité pelvienne du fœtus est en contact avec le détroit supérieur, la tête étant au fond utérin." },
    { id:"d24", cat:"defs", diff:2, q:"Définir la présentation de l'épaule",
      a:"Présentation oblique : la tête siège dans une fosse iliaque, le moignon de l'épaule répond au détroit supérieur. Repère : l'acromion." },
    { id:"d25", cat:"defs", diff:1, q:"Définir l'infertilité du couple",
      a:"Absence de grossesse chez un couple ayant des rapports réguliers et complets (≥ 3/semaine), sans contraception, pendant au moins 2 ans (J. Lansac)." },
    { id:"d26", cat:"defs", diff:1, q:"Définir l'anémie au cours de la grossesse (OMS)",
      a:"Taux d'hémoglobine < 11 g/dl chez la femme enceinte (OMS).", mnemo:"Hb < 11" },
    { id:"d27", cat:"defs", diff:2, q:"Définir le diabète gestationnel (OMS)",
      a:"Gestante dont la glycémie à jeun est > 1,20 g/dl (soit 6,5 mmol/l)." },
    { id:"d28", cat:"defs", diff:2, q:"Définir l'oligoamnios",
      a:"Le sac membraneux contient, dans le dernier mois de grossesse, moins de 200 ml de liquide amniotique." },
    { id:"d29", cat:"defs", diff:1, q:"Définir le fibrome utérin",
      a:"Tumeur bénigne développée à partir des éléments constitutifs du muscle utérin (myomètre)." },
    { id:"d30", cat:"defs", diff:2, q:"Définir la puberté",
      a:"Étape transitoire entre l'enfance et l'adolescence, caractérisée par la maturation de la fonction sécrétoire des gonades et l'acquisition de la fonction de reproduction." },
    { id:"d31", cat:"defs", diff:1, q:"Définir l'aménorrhée secondaire",
      a:"Absence de règles depuis plus de 3 à 6 mois chez une femme qui avait auparavant ses règles." },
    { id:"d32", cat:"defs", diff:1, q:"Définir l'aménorrhée primaire",
      a:"Absence de survenue de la ménarche (premières règles) à 16 ans." },

    /* ---------------- ACCOUCHEMENT & MÉCANIQUE ---------------- */
    { id:"a1", cat:"acc", diff:2, q:"Les 3 périodes de l'accouchement",
      a:"1. Effacement & dilatation du col (latence 0-4 cm, phase active 5-10 cm)\n2. Expulsion (de la dilatation complète à la naissance)\n3. Délivrance (sortie du placenta et des membranes)\nNB : périodes 1+2 = travail. Le bouchon muqueux signe le début du travail.", mnemo:"Dilatation → Expulsion → Délivrance" },
    { id:"a2", cat:"acc", diff:2, q:"Caractères des contractions utérines du travail",
      a:"• Involontaires\n• Rythmées\n• Intermittentes\n• Progressives (durée/intensité : 15-20 s → 60 s)\n• Totales\n• Douloureuses\n• Régulières (intervalle 15-20 min → 2-3 min)", mnemo:"IRI PTDR : Involontaires, Rythmées, Intermittentes, Progressives, Totales, Douloureuses, Régulières" },
    { id:"a3", cat:"acc", diff:2, q:"Repères des différentes présentations",
      a:"• Sommet → occiput\n• Bregma → grande fontanelle\n• Front → racine du nez\n• Face → menton\n• Épaule → acromion\n• Siège → sacrum", mnemo:"SO-BF-FN-FM-EA-SS" },
    { id:"a4", cat:"acc", diff:2, q:"Signe de Farabeuf (diagnostic d'engagement)",
      a:"Au TV, présentation engagée : les 2 doigts introduits sous la symphyse pubienne et dirigés vers la 2ᵉ vertèbre sacrée (S2) sont arrêtés par la présentation et ne trouvent pas de place entre celle-ci et la concavité sacrée." },
    { id:"a5", cat:"acc", diff:2, q:"Diagnostic clinique de l'engagement (palper + TV)",
      a:"• Palper : descente du moignon de l'épaule à < 7 cm (3 travers de doigt) du bord sup. de la symphyse\n• TV : signe de Farabeuf" },
    { id:"a6", cat:"acc", diff:2, q:"Indications et contre-indications de l'épreuve du travail",
      a:"Indications : bassin limite, bassin asymétrie légère/moyenne, bassin aplati, bassin transversalement rétréci, fœtus de poids normal, présentation du sommet.\nCI : présentation non céphalique, prématurité, souffrance fœtale, utérus cicatriciel, macrosomie, obstacle prævia." },
    { id:"a7", cat:"acc", diff:1, q:"Surveillance de l'épreuve du travail",
      a:"• Partogramme +++\n• Tocographie externe ou interne\n• RCF\n• Aspect du liquide amniotique" },
    { id:"a8", cat:"acc", diff:1, q:"À partir de quelle valeur la HU est-elle excessive à terme ?",
      a:"HU normales : 20 SA→16 cm, 24 SA→20, 28 SA→24, 32 SA→28, 36 SA→30, 40 SA→32-34 cm.\nEntre 4 et 7 mois : HU = âge (mois) × 4. HU excessive à terme : > 34 cm." },
    { id:"a9", cat:"acc", diff:2, q:"Étapes de l'examen obstétrical chez la gestante à terme",
      a:"1. Inspection de l'abdomen (cicatrices, forme)\n2. Mesure de la HU\n3. Palpation abdominale (volume, dos, présentation, LA)\n4. Auscultation des BDCF (dès 20-22 SA, base 120-160/min)\n5. Examen au spéculum\n6. Toucher vaginal" },
    { id:"a10", cat:"acc", diff:1, q:"Éléments du TV lors de l'examen obstétrical (3ᵉ trimestre)",
      a:"• Col utérin (position, longueur, consistance, ouverture)\n• Segment inférieur\n• Présentation fœtale, état des membranes, bassin osseux, tractus génital." },
    { id:"a11", cat:"acc", diff:1, q:"3 modifications du col au cours du travail",
      a:"1. Formation et ampliation du segment inférieur\n2. Effacement et dilatation du col\n3. Modification du pôle inférieur de l'œuf" },
    { id:"a12", cat:"acc", diff:2, q:"Les diamètres du détroit supérieur (mensurations normales)",
      a:"• Antéro-postérieurs : promonto-sus-pubien ≥ 11 cm ; promonto-rétro-pubien (PRP, utile) ≥ 10,5 cm\n• Transverses : transverse max 13,5 ; transverse antérieur 12 ; transverse médian (TM, utile) ≥ 12 cm\n• Obliques médians ≥ 12 cm\nPRP et TM = les 2 diamètres essentiels." },
    { id:"a13", cat:"acc", diff:2, q:"Les 3 phases cliniques de la délivrance",
      a:"1. Décollement (rétraction utérine = passive/permanente + contraction utérine)\n2. Expulsion (placenta tombe dans le segment inf. ; sortie mode Baudelocque [face fœtale] ou Duncan [face maternelle])\n3. Hémostase (rétraction utérine + thrombose physiologique, après vacuité utérine complète)" },
    { id:"a14", cat:"acc", diff:1, q:"Éléments du score d'APGAR",
      a:"• Fréquence cardiaque\n• Respiration\n• Tonus musculaire\n• Réactivité\n• Coloration", mnemo:"\"A Reçu Très Rapidement\" : Apparence(coloration), Respiration, Tonus, Réactivité, fréqCardiaque" },
    { id:"a15", cat:"acc", diff:2, q:"Soins systématiques du nouveau-né",
      a:"• Pansement ombilical ou clamp de Bard\n• Désobstruction bouche + VAS\n• Examen neurologique\n• Collyre aseptique\n• Vitamine K1\n• Mesures anthropométriques (PN, PC, PT, taille)" },
    { id:"a16", cat:"acc", diff:2, q:"Les différentes phases du cycle menstruel",
      a:"1. Folliculaire/proliférative (≈14 j, var. 11-21) : ↑FSH → croissance folliculaire + œstrogènes\n2. Ovulatoire : pic de LH (+ pic FSH), rupture folliculaire = ponte\n3. Lutéale/sécrétoire (14 j, stable) : corps jaune → progestérone, endomètre prêt à la nidation\n4. Menstruation : chute œstrogènes + progestérone → règles" },

    /* ---------------- PRÉSENTATIONS DYSTOCIQUES ---------------- */
    { id:"pd1", cat:"presD", diff:2, q:"Éléments à rechercher au TV : présentation de la face",
      a:"Pendant la grossesse : présentation élevée, segment inf. épais.\nPendant le travail : présentation longtemps élevée, poche des eaux volumineuse et bombante ; les doigts perçoivent front, nez, narines, bouche et surtout le menton (repère) en \"fer à cheval\" ; pas de fontanelle perçue." },
    { id:"pd2", cat:"presD", diff:2, q:"Conditions d'accouchement de la présentation de face",
      a:"• Déflexion maximale de la tête\n• Menton tourné vers l'avant, calé sous la symphyse\n• Engagement par le diamètre sous-mento-bregmatique\n• Rotation en avant et haute" },
    { id:"pd3", cat:"presD", diff:2, q:"3 conditions d'AVB d'une présentation du siège",
      a:"• Bassin maternel normal\n• Pas de macrosomie (Pf entre 2500 et 3000 g)\n• Pas de disproportion fœto-pelvienne\n• Progression normale de la dilatation\n• Pas de souffrance fœtale" },
    { id:"pd4", cat:"presD", diff:2, q:"3 complications de la présentation du siège",
      a:"• Rétention de la tête dernière\n• Relèvement des bras\n• Arrêt de la progression" },
    { id:"pd5", cat:"presD", diff:2, q:"Modalités de l'accouchement du siège",
      a:"• Dilatation complète\n• Prise de contact présentation/périnée\n• Épisiotomie systématique\n• Administration d'ocytocine\n• Effort expulsif lors des CU\n• Abstention jusqu'à la pointe de l'omoplate\n• Présence d'un pédiatre/réanimateur" },
    { id:"pd6", cat:"presD", diff:2, q:"Causes maternelles et fœtales de la présentation du siège",
      a:"• Maternelles : utérines (fibromes, multiparité), causes pelviennes (obstacle)\n• Fœtales : malformatives (×2-3 vs céphalique), atteintes neuro, prématurité, grossesse multiple, déflexion primitive de la tête" },
    { id:"pd7", cat:"presD", diff:2, q:"Éléments de l'épaule négligée",
      a:"• Présentation de l'épaule\n• Femme en travail depuis longtemps\n• Membranes rompues\n• Utérus rétracté\n• Infection ovulaire\n• Fœtus mort" },
    { id:"pd8", cat:"presD", diff:2, q:"3 étiologies de la présentation de l'épaule",
      a:"• Maternelles : multiparité, obstacles prævia, malformations utérines\n• Fœto-annexielles : hydramnios, grossesse multiple, prématurité, malformations (anencéphalie, hydrocéphalie)\n• Materno-fœtales : DFP" },
    { id:"pd9", cat:"presD", diff:2, q:"CAT devant la présentation de l'épaule",
      a:"• Césarienne immédiate\n• Versions transformant la présentation transversale en longitudinale : VME, VMI (grande extraction du siège)\n• Épaule négligée : embryotomie possible" },

    /* ---------------- URGENCES HÉMORRAGIQUES ---------------- */
    { id:"u1", cat:"urg", diff:2, q:"Définir le HRP",
      a:"Hématome rétro-placentaire (DPPNI) : accident paroxystique du dernier trimestre ou du travail, décollement prématuré d'un placenta normalement inséré avec hématome entre placenta et paroi utérine." },
    { id:"u2", cat:"urg", diff:2, q:"Classification de SHER du HRP (grades)",
      a:"• Grade 1 : métrorragies apparemment isolées\n• Grade 2 : tableau plus complet avec enfant vivant\n• Grade 3A : enfant mort, pas de trouble de coagulation\n• Grade 3B : enfant mort + trouble de coagulation" },
    { id:"u3", cat:"urg", diff:2, q:"4 signes physiques de l'HRP",
      a:"• HU qui augmente entre 2 mesures\n• Utérus hypertonique (\"utérus de bois\")\n• Au TV : segment inf. dur, tendu (\"sébile de bois\")\n• Si col ouvert : poche des eaux perçue et tendue", mnemo:"Utérus de BOIS" },
    { id:"u4", cat:"urg", diff:2, q:"4 complications maternelles du HRP",
      a:"• Troubles de la coagulation\n• Atonie / nécrose utérine\n• État de choc grave avec nécrose des corticales rénales\n• Décès maternel" },
    { id:"u5", cat:"urg", diff:3, q:"CAT devant un HRP à 3 cm avec fœtus vivant",
      a:"Mesures générales : 2 VVP (G18) + bilan (GS/Rh, NFS, test de coagulation au lit) ; remplissage RL/SSI 20 ml/kg en 15-20 min (×1 si besoin) ; acide tranexamique 1 g sur 20 min ; vitamine K1 10 mg IVL ; transfusion objectif 9 g/dl (ratio CGR/PFC = 1, plaquettes si < 50 000) ; fibrinogène si < 1 g/l (objectif 2) ; sonde urinaire ; O2 en DLG.\nObstétrical : fœtus vivant = césarienne d'urgence." },
    { id:"u6", cat:"urg", diff:2, q:"CAT devant un HRP grade 2",
      a:"• TRT médical toujours indiqué, adapté à l'état clinique (PEC du choc)\n• TRT obstétrical : césarienne si fœtus vivant\n• Si dilatation avancée : césarienne\n• Centre sans bloc : rompre les membranes avant évacuation\n• Examiner le placenta, mesurer la cupule, peser le caillot" },
    { id:"u7", cat:"urg", diff:2, q:"Différence HRP vs Placenta prævia (PP)",
      a:"PP : saignement indolore, rougeâtre, après rapports/TV, pas d'HTA, état clinique proportionnel au sang extériorisé, utérus souple, BDCF perçus.\nHRP : saignement + douleur intense, noirâtre, sans signe prémonitoire, souvent HTA/toxémie, choc disproportionné, utérus de bois, BDCF absents." },
    { id:"u8", cat:"urg", diff:2, q:"Étiologies du placenta prævia",
      a:"Synéchies ; ATCD d'endométrite ; grossesses multiples ; ablation de myome intra-cavitaire ; fibrome ; malformation utérine.", mnemo:"SAGA-FM : Synéchies, Antécédent endométrite, Grossesses multiples, Ablation myome, Fibrome, Malformation" },
    { id:"u9", cat:"urg", diff:1, q:"3 indications de césarienne en cas de PP",
      a:"• PP recouvrant\n• PP non recouvrant avec hémorragie persistante\n• Hémorragie importante (césarienne de sauvetage maternel)" },
    { id:"u10", cat:"urg", diff:2, q:"6 étiologies des hémorragies de la délivrance",
      a:"• Traumatiques : déchirure col/vagin/vulve, thrombus\n• Toniques : inertie/atonie utérine\n• Rétention placentaire : PP, accreta, increta\n• Troubles de la coagulation\n• Inversion utérine", mnemo:"4 T : Tonus, Tissu (rétention), Trauma, Thrombine (coag)" },
    { id:"u11", cat:"urg", diff:3, q:"CAT devant une hémorragie de la délivrance",
      a:"Préventif : GATPA + surveillance.\nGestes d'urgence : appeler à l'aide ; évaluer le choc ; masser l'utérus ; 10 UI ocytocine IM ; VVP G16 + RL ; sonder ; vérifier/examiner le placenta ; examiner col + périnée ; test de coagulation au lit.\nInertie : remplissage + massage + misoprostol 800 µg SL ; compression bimanuelle / tamponnement (ballonnet de Bakri) ; transfusion ; ligature artère utérine/utéro-ovarienne ou hystérectomie." },
    { id:"u12", cat:"urg", diff:2, q:"Complications de la délivrance",
      a:"• Rétention placentaire\n• Hémorragie de la délivrance\n• Inversion utérine\n• Placenta accreta" },
    { id:"u13", cat:"urg", diff:2, q:"Signes du syndrome de pré-rupture utérine",
      a:"• Accentuation de la rétraction utérine\n• Corps utérin de plus en plus dur, hypertonie permanente\n• Segment inf. s'allonge/s'amincit → utérus en sablier (signe de Bandl-Frommel)\n• Tension des ligaments ronds\n• BDCF ralentis ou absents", mnemo:"BANDL-FROMMEL = utérus en sablier" },
    { id:"u14", cat:"urg", diff:2, q:"Signes de rupture utérine",
      a:"• Douleur abdominale brutale en coup de poignard, suivie d'accalmie\n• Sensation d'eau chaude dans le ventre\n• Hémorragie génitale (jus de réglisse)\n• Signes de choc\n• Utérus irrégulier, fœtus palpé sous la peau\n• BDCF absents\n• TV : disparition de la présentation" },
    { id:"u15", cat:"urg", diff:2, q:"Étiologies des ruptures utérines",
      a:"• Maternelles : multiparité, altération du muscle utérin, obstacles prævia, manœuvre abortive, déchirure du col\n• Fœtales : macrosomie, présentation vicieuse (front, épaule, face enclavée), hydrocéphalie, malformation\n• Iatrogènes : usage non contrôlé des utérotoniques" },
    { id:"u16", cat:"urg", diff:1, q:"4 diagnostics différentiels de la rupture utérine",
      a:"• Hématome rétro-placentaire\n• Placenta prævia\n• Hémorragie de Benkiser\n• Déchirure du col ou du vagin" },
    { id:"u17", cat:"urg", diff:1, q:"Étiologies des hémorragies du 1ᵉʳ trimestre",
      a:"• GEU, grossesse molaire, avortement\n• Cancer du col, polype du col, cervicite" },
    { id:"u18", cat:"urg", diff:1, q:"Étiologies des hémorragies du 3ᵉ trimestre",
      a:"• HRP, placenta prævia, rupture utérine\n• Cancer du col, polype du col, cervicite" },
    { id:"u19", cat:"urg", diff:2, q:"Signes de GEU rompue",
      a:"• Douleurs abdominales mal localisées irradiant lombes/épigastre/épaules\n• Signes de choc (hémorragique), anémie\n• Syndrome d'irritation péritonéale (cri du Douglas, cri de l'ombilic, météorisme)\n• Culdocentèse positive : sang noirâtre incoagulable" },
    { id:"u20", cat:"urg", diff:2, q:"Signes cliniques de la GEU non rompue",
      a:"• Métrorragies noires (sépia), intermittentes\n• Douleurs pelviennes d'intensité variable, calmées par l'émission de sang\n• Signes sympathiques de grossesse (nausées, seins tendus)\nParaclinique : β-HCG > 20 mUI/l, échographie." },
    { id:"u21", cat:"urg", diff:1, q:"4 facteurs de risque de GEU",
      a:"• IST, salpingites, endométrites\n• ATCD de chirurgie tubaire/pelvienne\n• Altération de la paroi tubaire\n• Tabac\n• DIU" },
    { id:"u22", cat:"urg", diff:2, q:"Gestes à faire en cas d'hydramnios",
      a:"• Ponction abdominale répétée (100-200 cc)\n• Rompre largement les membranes\n• Position de Trendelenburg" },
    { id:"u23", cat:"urg", diff:1, q:"3 facteurs étiologiques de la procidence du cordon",
      a:"• Maternels : bassins rétrécis, grande multiparité, obstacles prævia (kystes, fibromes)\n• Fœtaux : présentation du siège (~4%), épaule (2,5-8%), prématurité (7%), grossesses multiples\n• Annexiels : hydramnios, cordon long, placenta prævia, RPM" },
    { id:"u24", cat:"urg", diff:1, q:"Différence procidence vs procubitus du cordon",
      a:"• Procidence : chute du cordon en avant de la présentation, membranes ROMPUES\n• Procubitus : chute du cordon en avant de la présentation, membranes INTACTES" },

    /* ---------------- PRÉÉCLAMPSIE / HTA ---------------- */
    { id:"e1", cat:"pe", diff:2, q:"Définir le HELLP syndrome + contexte",
      a:"Haemolysis, Elevated Liver enzymes, Low Platelets :\n• Hémolyse (anémie, ictère, ↑bilirubine indirecte)\n• ↑transaminases\n• Thrombopénie < 100 000/mm³\nComplique surtout la prééclampsie ; survient du 2ᵉ trimestre au 8ᵉ jour du post-partum.", mnemo:"H-EL-LP" },
    { id:"e2", cat:"pe", diff:2, q:"4 complications maternelles de la prééclampsie sévère",
      a:"• Éclampsie\n• HELLP syndrome\n• Insuffisance rénale aiguë\n• AVC\n• Lésions rétiniennes\n• Hématome rétro-placentaire" },
    { id:"e3", cat:"pe", diff:2, q:"Critères de sévérité de la prééclampsie (maternels)",
      a:"• PAS ≥ 160 et/ou PAD ≥ 110 mmHg\n• Protéinurie ≥ 3 g/24h\n• Signes fonctionnels d'HTA : céphalées, acouphènes, troubles visuels\n• Douleur épigastrique en barre (signe de Chaussier)\n• ROT vifs\n• Oligurie < 400 ml/24h", mnemo:"Douleur en barre = signe de CHAUSSIER" },
    { id:"e4", cat:"pe", diff:2, q:"Critères de sévérité fœtaux de la prééclampsie",
      a:"• Doppler ombilical pathologique (diastole nulle, reverse flow)\n• RCIU sévère\n• Oligoamnios sévère\n• Anamnios" },
    { id:"e5", cat:"pe", diff:3, q:"Protocole sulfate de magnésium (but, administration, surveillance)",
      a:"But : prévenir/arrêter les convulsions.\nCharge : 4 g IV lente en 15 min + 5 g IM profonde dans chaque fesse (10 g) avec 1 ml lidocaïne 2%.\nEntretien : 5 g IM (sol. 50% + lidocaïne) toutes les 4h, en alternant les fesses ; poursuivre 24h après l'accouchement ou la dernière convulsion.\nSurveillance : FR ≥ 16/min, ROT présents, diurèse ≥ 30 ml/h.", mnemo:"FR – ROT – Diurèse" },
    { id:"e6", cat:"pe", diff:1, q:"Complications de l'HTA pendant la grossesse",
      a:"Éclampsie ; HELLP syndrome ; coagulopathies ; AVC ; décès maternel ; mort fœtale ; prématurité ; RCIU." },

    /* ---------------- POST-PARTUM & SUITES ---------------- */
    { id:"p1", cat:"pp", diff:2, q:"Définir la GATPA + ses étapes",
      a:"Gestion Active de la Troisième Période de l'Accouchement :\n1. S'assurer de l'absence d'un autre enfant\n2. 10 UI d'ocytocine IM dans les minutes suivant l'accouchement\n3. Enrouler le cordon autour d'une pince + attendre une contraction\n4. Traction contrôlée du cordon en refoulant l'utérus vers le haut\n5. Massage utérin à travers la paroi abdominale\n6. Examiner le placenta\n7. Examiner la filière génitale" },
    { id:"p2", cat:"pp", diff:2, q:"Signes physiques de l'endométrite du post-partum",
      a:"• Utérus gros, mal involué, mou, douloureux\n• Col béant\n• Lochies fétides" },
    { id:"p3", cat:"pp", diff:2, q:"4 signes cliniques d'endométrite",
      a:"• Fièvre (≈38,5°C le soir)\n• Utérus mal involué (gros, mou, douloureux à la mobilisation)\n• Écoulement purulent au niveau de la plaie opératoire\n• Lochies fétides et/ou purulentes\n• ± saignements utérins" },
    { id:"p4", cat:"pp", diff:1, q:"4 signes de danger maternel dans le post-partum",
      a:"• Saignement vaginal important\n• Fièvre\n• Pertes vaginales malodorantes\n• Violents maux de tête, troubles auditifs/visuels\n• Seins chauds ou douloureux" },
    { id:"p5", cat:"pp", diff:2, q:"Éléments de surveillance dans les suites de couches",
      a:"• Les constantes\n• Le saignement vaginal (lochies)\n• Le globe de sécurité\n• L'allaitement\n• Les cuisses et mollets\n• Les réactions psychologiques", mnemo:"\"Globe, Saignement, Constantes, Seins, Mollets, Psy\"" },
    { id:"p6", cat:"pp", diff:2, q:"Aspect des lochies selon le jour",
      a:"• Sanglantes : J0–J2\n• Séro-sanguinolentes : J3–J8\n• Séreuses : J9–J15" },
    { id:"p7", cat:"pp", diff:2, q:"Périodicité de surveillance des constantes (accouchée récente)",
      a:"6 premières heures intensives :\n• Toutes les 15 min pendant 2h\n• Toutes les 30 min pendant 1h\n• Toutes les heures pendant 3h", mnemo:"15min×2h / 30min×1h / 1h×3h" },
    { id:"p8", cat:"pp", diff:1, q:"Le baby blues",
      a:"Angoisse, troubles du sommeil, troubles de l'humeur, irritabilité, survenant au 3ᵉ jour du post-partum." },
    { id:"p9", cat:"pp", diff:1, q:"Conseils dans le post-partum (signes de danger nouveau-né)",
      a:"• Difficulté respiratoire\n• Peau bleue ou jaune\n• Convulsions\n• Saignement du cordon ombilical\n• Corps chaud ou froid\n• Yeux gonflés/collants avec pus" },
    { id:"p10", cat:"pp", diff:2, q:"SPO immédiats chez une césarisée (prescription)",
      a:"• Ceftriaxone 2 g/24h\n• Paracétamol 1 g + néfopam 20 mg /8h\n• Solutés 3 L/24h (SSI 500 + RL 500 + SGI 500)\n• Énoxaparine 0,4 ml/24h jusqu'à la marche\n• Misoprostol 3 cp en sublingual\n• Ocytocine 10 UI/8h\n• AINS suppo 1/12h" },
    { id:"p11", cat:"pp", diff:1, q:"Surveillance des SPO immédiats chez une césarisée",
      a:"Conscience, état général, TA, température, pansement, globe utérin, saignement vaginal, difficultés respiratoires, convulsions, sonde vésicale, reprise du transit, cuisses et mollets." },
    { id:"p12", cat:"pp", diff:2, q:"Avantages du lait maternel",
      a:"Température stable, adapté aux besoins, lait frais vivant, économique, nutritif, facile à digérer, limite les diarrhées, idéal pour la relation mère-enfant, anticorps adaptés, réduit les allergies, espacement naturel des naissances." },
    { id:"p13", cat:"pp", diff:2, q:"Définir les suites de couches",
      a:"Période allant de l'accouchement à la première menstruation (retour de couches), ou plus globalement jusqu'au retour à l'état antérieur des fonctions féminines (Lansac)." },
    { id:"p14", cat:"pp", diff:1, q:"CAT chez une femme porteuse de stérilet infecté",
      a:"• Retirer le stérilet\n• Traiter l'infection\n• Proposer une autre méthode contraceptive" },

    /* ---------------- AVORTEMENT & SAA ---------------- */
    { id:"av1", cat:"avort", diff:2, q:"4 complications de l'avortement clandestin",
      a:"• Immédiates : hémorragie utérine/intra-abdominale, perforation utérine + choc, décès (embolie gazeuse, réflexe vagal)\n• Secondaires : endométrite, salpingite, pelvipéritonite, abcès pelvien, péritonite, septicémie, tétanos\n• Tardives : iso-immunisation Rh, GEU, avortements spontanés, infertilité par salpingite" },
    { id:"av2", cat:"avort", diff:2, q:"Phases cliniques de l'avortement (menace)",
      a:"Menace : aménorrhée, douleurs pelviennes (coliques), métrorragies minimes rouges/rosées, TV : col long, ramolli et FERMÉ, utérus en rapport avec l'âge, β-HCG élevés." },
    { id:"av3", cat:"avort", diff:2, q:"Avortement en cours / inévitable",
      a:"Aménorrhée, douleurs expulsives, métrorragies abondantes rouge vif, TV : col court, ramolli, OUVERT avec perception du produit de conception, utérus non en rapport avec l'âge. Écho : œuf dans le canal cervical." },
    { id:"av4", cat:"avort", diff:2, q:"Avortement incomplet vs complet",
      a:"• Incomplet : métrorragies minimes + débris ovulaires, col ramolli FERMÉ, utérus de volume réduit, écho : débris dans la cavité.\n• Complet : expulsion à domicile, saignement minime, absence de débris, col fermé, écho confirme la vacuité." },
    { id:"av5", cat:"avort", diff:2, q:"Composantes des soins après avortement (SAA)",
      a:"• Traitement d'urgence\n• Counseling\n• Planification familiale\n• Liens avec les autres services de SR\n• Implication de la communauté", mnemo:"\"Très Curieux, Plein de Liens Communautaires\"" },
    { id:"av6", cat:"avort", diff:1, q:"Signes de danger après AMIU",
      a:"• Crampes prolongées\n• Saignements > 2 semaines ou plus abondants qu'une règle\n• Douleur aiguë ou accrue\n• Fièvre, frissons, malaise, évanouissement\n• Syncope" },
    { id:"av7", cat:"avort", diff:1, q:"Conseils à une fille de 14 ans demandant un APC",
      a:"• S'enquérir des raisons de son avortement\n• La dissuader en expliquant les risques encourus\n• Lui faire savoir que l'avortement est illégal au Burkina Faso" },
    { id:"av8", cat:"avort", diff:2, q:"Définir et surveiller la grossesse molaire",
      a:"Définition : dégénérescence kystique (hyperplasie + dystrophie + dysfonction vasculaire des villosités choriales).\nSurveillance clinique : ↓métrorragies, involution utérine, régression des kystes ovariens. Paraclinique : courbe β-HCG (hebdo jusqu'à négativation puis mensuel 12-18 mois), écho, RP." },

    /* ---------------- CÉSARIENNE & GESTES ---------------- */
    { id:"c1", cat:"cesar", diff:1, q:"5 indications de césarienne prophylactique (programmée)",
      a:"• Utérus cicatriciel\n• Grossesse gémellaire\n• Macrosomie\n• Présentation du siège\n• Transmission mère-enfant d'infections" },
    { id:"c2", cat:"cesar", diff:2, q:"Indications absolues vs relatives de la césarienne",
      a:"Absolues : bassin généralement rétréci, bassin très asymétrique, PP recouvrant, HRP fœtus vivant, procidence du cordon battant à petite dilatation, SFA à petite dilatation, présentation front/épaule/face enclavée.\nRelatives : échec épreuve du travail, échec TRT médical (HRP/PP/toxémie), macrosomie chez primipare, HTA mal contrôlée, diabète mal équilibré, cardiopathie décompensée." },
    { id:"c3", cat:"cesar", diff:2, q:"Outils de la boîte de césarienne",
      a:"Lame de bistouri, porte-aiguilles + fils, pince de Kocher, pince de Farabeuf, pince à disséquer, ciseaux, pince à peau, pince à cœur, valve sous-pubienne." },
    { id:"c4", cat:"cesar", diff:2, q:"Gestion devant une SFA à petite dilatation",
      a:"Médical : DLG, O2 6-8 L, SGH 10% 500cc, sérum bicarbonaté, préparer la réanimation du nné.\nObstétrical : SFA < 6 cm → césarienne ; 7-10 cm → césarienne si pas d'accouchement en 1h ; phase terminale → AVB instrumental (ventouse) ± ocytociques." },
    { id:"c5", cat:"cesar", diff:1, q:"Définir la révision utérine vs délivrance artificielle",
      a:"• DA : extraction manuelle du placenta non décollé.\n• RU : exploration manuelle de la cavité utérine (débris, caillots)." },

    /* ---------------- INFECTIONS / RPM / PALU / VIH ---------------- */
    { id:"i1", cat:"infect", diff:2, q:"Définir la RPM + CAT avant 34 SA (principe)",
      a:"Définition : rupture du chorion et de l'amnios au pôle inférieur de l'œuf, ≥ 24h avant tout début de travail.\nBilan : PV + ATB/ATF, ECBU, NFS, CRP, GS/Rh, RAI, glycémie, Promtest (pH vaginal > 8), écho. Éviter les TV (gants stériles si nécessaires)." },
    { id:"i2", cat:"infect", diff:3, q:"CAT RPM entre 28 et 32 SA",
      a:"Prématurité sévère : hospitalisation + garnitures propres + repos strict (Trendelenburg) + énoxaparine 0,4 ml SC/24h + antibioprophylaxie érythromycine 500 mg/12h + maturation pulmonaire (bétaméthasone 12 mg IM ×2 à 24h) + maturation cérébrale (sulfate de Mg si < 32 SA) + tocolyse si CU (nifédipine ou salbutamol)." },
    { id:"i3", cat:"infect", diff:3, q:"CAT RPM 32-34 SA et après 34 SA",
      a:"32-34 SA (préma moyenne) : hospitalisation + ceftriaxone 2 g/24h + bétaméthasone 12 mg ×2 + déclenchement ou césarienne d'urgence.\n> 34 SA : hospitalisation + ceftriaxone 2 g/24h + expectative 48h + score de Bishop → déclenchement ou césarienne." },
    { id:"i4", cat:"infect", diff:1, q:"Complications de la RPM",
      a:"• Chorioamniotite\n• Embolie amniotique\n• Procidence du cordon\n• Présentation vicieuse" },
    { id:"i5", cat:"infect", diff:2, q:"Chimioprophylaxie anti-palustre chez la femme enceinte (TPI)",
      a:"TPI : sulfadoxine 500 mg – pyriméthamine 25 mg (SP), 3 cp en prise unique mensuelle dès la 16ᵉ SA (ou après les MAF), jusqu'au 42ᵉ jour post-partum. Intervalle 24h avec l'acide folique. CI : 1ᵉʳ trimestre, allergie aux sulfamides. Si VIH sous cotrimoxazole : pas de SP." },
    { id:"i6", cat:"infect", diff:2, q:"Complications du paludisme chez la femme enceinte",
      a:"• 6 premiers mois : aggravation des signes de grossesse, anémie, avortement, MFIU\n• 6-9 mois : accouchement prématuré, hémorragie, palu congénital, dystocie dynamique\n• Post-partum : ↓lochies, ↓montée laiteuse, infection puerpérale" },
    { id:"i7", cat:"infect", diff:2, q:"PTME : que faire en salle d'accouchement (À FAIRE)",
      a:"• Respecter la poche des eaux jusqu'à dilatation complète\n• Désinfecter les voies génitales (polyvidone iodée)\n• Partogramme\n• Antibioprophylaxie large spectre\n• GATPA" },
    { id:"i8", cat:"infect", diff:2, q:"PTME : que faire en salle d'accouchement (À ÉVITER)",
      a:"Gestes traumatiques (TV intempestifs, forceps/ventouse, versions), travail prolongé, RAM avant dilatation complète, blessure du scalp, traire le cordon, mêmes ciseaux pour épisiotomie et cordon. Épisiotomie/ocytocine avant expulsion à éviter autant que possible." },
    { id:"i9", cat:"infect", diff:2, q:"4 barrières de prévention des infections nosocomiales",
      a:"• Hygiène des mains (savon + SHA)\n• Équipements de protection individuelle (gants, masques, blouses, lunettes)\n• Asepsie et désinfection (stérilisation, désinfection des surfaces)\n• Isolement des patientes infectées (isolement septique)" },
    { id:"i10", cat:"infect", diff:1, q:"4 complications d'une infection urinaire basse sur grossesse",
      a:"RPM, chorioamniotite, MAP, accouchement prématuré, avortement." },
    { id:"i11", cat:"infect", diff:2, q:"Facteurs favorisant l'IU pendant la grossesse",
      a:"• Compression urétérale (à droite)\n• Dilatation physiologique\n• Ascension de la vessie → dysurie\n• Étirement des uretères → reflux vésico-urétéral\n• Progestérone myorelaxante → stase urétérale" },
    { id:"i12", cat:"infect", diff:2, q:"ISO (infection du site opératoire) : grades + traitement",
      a:"ISO = infection d'incision dans les 30 j (90 j si matériel).\n• ISO 1 (superficielle : peau + sous-cutané)\n• ISO 2 (profonde : fascia + muscles) → bi-ATB : métronidazole 500 mg/8h + amox-ac. clav. 1,2 g/8h, pansement Dakin\n• ISO 3 (organes/espaces) → tri-ATB : + gentamicine 160 mg/24h" },
    { id:"i13", cat:"infect", diff:1, q:"Traitement d'une cervicite à trichomonas",
      a:"Traiter la patiente ET son/ses partenaire(s) : métronidazole 2 g en dose unique." },
    { id:"i14", cat:"infect", diff:1, q:"Vaccins autorisés pendant la grossesse",
      a:"Antigrippal ; polio injectable ; Typhim Vi ; VAT ; anti-hépatite B ; anti-méningocoque." },

    /* ---------------- CONTRACEPTION & PF ---------------- */
    { id:"co1", cat:"contra", diff:2, q:"3 modalités de contraception d'urgence (+ délais)",
      a:"• Lévonorgestrel (Norlevo) : dans les 3 jours\n• Acétate d'ulipristal (Ella One) : dans les 5 jours\n• DIU : dans les 5 jours après le rapport à risque", mnemo:"Pilule 3j / Ella 5j / DIU 5j" },
    { id:"co2", cat:"contra", diff:1, q:"Contraception chez une femme HTA",
      a:"Exclure les œstroprogestatifs. Proposer : méthode naturelle, méthode barrière, progestatif seul, DIU." },
    { id:"co3", cat:"contra", diff:1, q:"Contraception moderne chez la femme à J1 du post-partum",
      a:"DIU." },

    /* ---------------- CANCERS & TUMEURS ---------------- */
    { id:"on1", cat:"onco", diff:2, q:"3 signes cliniques du cancer du sein",
      a:"• SF : douleur mammaire, écoulement mamelonnaire\n• SG : AEG\n• SP : ↑volume/ascension du sein, peau d'orange, ulcération, rétraction du mamelon, écoulement unilatéral unicanalaire, nodule dur mal limité adhérent, ADP axillaires/sus-claviculaires" },
    { id:"on2", cat:"onco", diff:1, q:"Forme histologique du cancer du col",
      a:"Carcinome épidermoïde (spinocellulaire)." },
    { id:"on3", cat:"onco", diff:1, q:"Forme histologique du cancer du col (rappel) + 4 moyens de prévention primaire",
      a:"Prévention primaire : vaccination anti-HPV ; limiter l'exposition au HPV (préservatif, abstinence, réduction du nombre de partenaires)." },
    { id:"on4", cat:"onco", diff:2, q:"Facteurs de risque du cancer du col",
      a:"Rapports sexuels multiples et précoces, bas niveau socio-économique, grande multiparité, infections cervicales (HPV, herpès), dysplasie cervicale." },
    { id:"on5", cat:"onco", diff:2, q:"Classification FIGO du cancer du col",
      a:"• Stade 0 : in situ\n• Stade I : limité au col (Ia histologique, Ib clinique)\n• Stade II : vagin (2/3 sup) et paramètres (IIa/IIb)\n• Stade III : 1/3 inf. vagin ou paroi pelvienne (hydronéphrose)\n• Stade IV : organes voisins (IVa vessie/rectum, IVb métastases)" },
    { id:"on6", cat:"onco", diff:2, q:"Classification TNM du cancer du sein (T et N)",
      a:"T : T0 (pas de tumeur), Tis (in situ), T1 ≤ 2 cm, T2 (2-5 cm), T3 > 5 cm, T4 (extension paroi/peau).\nN : N0 (pas d'ADP), N1 (axillaire mobile), N2 (axillaire fixée), N3 (mammaire interne).\nM : M0 / M1 (métastases à distance)." },
    { id:"on7", cat:"onco", diff:1, q:"Principes de dépistage d'un cancer",
      a:"• Cancer fréquent (col, sein)\n• Moyen de dépistage simple, fiable, reconnu\n• Cancer accessible au dépistage\n• Le dépistage doit améliorer le pronostic (traitement disponible)" },
    { id:"on8", cat:"onco", diff:2, q:"Complications des kystes ovariens",
      a:"• Torsion\n• Hémorragie intra-kystique\n• Rupture (hémorragique)\n• Infection\n• Compression des organes de voisinage" },
    { id:"on9", cat:"onco", diff:2, q:"Complications des fibromes utérins",
      a:"Hémorragies, compression mécanique (rectum, vessie, urètre), accidents thromboemboliques, avortements, RPM, PP, endométrite, nécrobiose, dégénérescence." },
    { id:"on10", cat:"onco", diff:2, q:"Diagnostic anatomo-topographique des fibromes",
      a:"• Sous-séreux : sous le péritoine (sessile ou pédiculé)\n• Interstitiel : dans le myomètre\n• Sous-muqueux : dans la cavité, hémorragies importantes (sessile ou pédiculé comme un polype)" },
    { id:"on11", cat:"onco", diff:2, q:"Signes cliniques de l'adénofibrome du sein",
      a:"Âge 20-30 ans ; tuméfaction de 3-4 cm unique, bien limitée, ferme, indolore, mobile, sans signes cutanés ni adénopathies." },
    { id:"on12", cat:"onco", diff:2, q:"Facteurs de risque du cancer du sein",
      a:"Multiparité (paradoxal : nulliparité aussi), première grossesse tardive, absence d'allaitement, vie génitale prolongée, ATCD familiaux, gènes BRCA1 & 2." },
    { id:"on13", cat:"onco", diff:1, q:"Étapes de l'examen du sein",
      a:"• Inspection : volume, parité, symétrie, coloration\n• Palpation : bilatérale et comparative des cadrans + aires ganglionnaires (nodule)\n• Pression des mamelons (écoulement)" },
    { id:"on14", cat:"onco", diff:1, q:"3 contre-indications de l'hystérosalpingographie",
      a:"• Grossesse\n• Infection pelvienne active\n• Allergie à l'iode / produits de contraste\n(+ hémorragies utérines abondantes, opacification digestive récente)" },

    /* ---------------- GYNÉCO MÉDICALE ---------------- */
    { id:"g1", cat:"gyn", diff:2, q:"Causes de l'aménorrhée secondaire (hors grossesse)",
      a:"Syndrome des ovaires micro-polykystiques, insuffisance ovarienne primitive, hyperprolactinémie, anorexie mentale, hypogonadisme hypogonadotrope, exercice physique intense, ménopause, tuberculose génitale." },
    { id:"g2", cat:"gyn", diff:2, q:"Causes de l'aménorrhée primaire + malformations",
      a:"Insuffisance ovarienne, hypogonadisme hypogonadotrope, SOPK, insuffisance antéhypophysaire, hyperprolactinémie, anorexie.\nMalformations : imperforation de l'hymen, atrésie/absence congénitale de vagin, anomalies du col, syndrome de Turner (1 seul chromosome X)." },
    { id:"g3", cat:"gyn", diff:2, q:"6 conditions pour obtenir les menstruations",
      a:"• Vagin perméable\n• Utérus fonctionnel, endomètre réceptif\n• Ovaires sécrétoires\n• Hypophyse intacte\n• Hypothalamus normal\n• Cortex non perturbé" },
    { id:"g4", cat:"gyn", diff:2, q:"Conditions pour une fécondation chez la femme",
      a:"• Ovulation régulière de qualité\n• Trompes perméables\n• Appareil génital permettant les rapports (contact spermatozoïdes-glaire)\n• Glaire cervicale de bonne qualité\n• Muqueuse utérine réceptive (nidation)" },
    { id:"g5", cat:"gyn", diff:2, q:"Conditions pour une fécondation chez l'homme",
      a:"• Testicule normal\n• Sécrétion normale de FSH et testostérone\n• Liquide séminal de bonne qualité\n• Absence d'anomalie de l'épididyme/déférents/canaux éjaculateurs\n• Absence d'anomalie de l'éjaculation (éjaculation rétrograde)" },
    { id:"g6", cat:"gyn", diff:1, q:"Définir azoospermie, oligospermie, tératospermie",
      a:"• Azoospermie : absence de spermatozoïdes\n• Oligospermie : < 15 millions de spz/ml\n• Tératospermie : < 4% de formes typiques" },
    { id:"g7", cat:"gyn", diff:1, q:"Causes d'algies pelviennes",
      a:"• Aiguës : GEU, menace d'avortement, rupture kystique, endométrite, torsion d'annexe, salpingite\n• Chroniques : endométriose, dysménorrhée, dystrophie ovarienne" },
    { id:"g8", cat:"gyn", diff:2, q:"3 causes de puberté précoce vraie et 3 causes de retard pubertaire",
      a:"• PP vraie : tumeurs cérébrales (hamartome, gliome du chiasma, craniopharyngiome), hydrocéphalie, hypothyroïdie infantile\n• Retard : malformations/tumeurs hypophysaires, anorexie mentale, syndrome de Morris (testicule féminisant), syndrome de Rokitansky-Küster-Hauser (absence d'utérus)" },
    { id:"g9", cat:"gyn", diff:2, q:"Les 4 manifestations de la puberté normale",
      a:"• Maturation des organes génitaux\n• Apparition des caractères sexuels secondaires\n• Croissance staturo-pondérale\n• Manifestations psychiques" },
    { id:"g10", cat:"gyn", diff:1, q:"Décrire la bouffée de chaleur de la ménopause",
      a:"Bouffées de chaleur avec sueurs nocturnes, vertiges, HTA, irritabilité." },
    { id:"g11", cat:"gyn", diff:1, q:"Intérêt du dosage plasmatique des β-HCG",
      a:"Spécificité/sensibilité bonnes pour des taux > 20 mUI/l ; leur présence confirme l'existence de tissu trophoblastique." },
    { id:"g12", cat:"gyn", diff:1, q:"Touchers pelviens : éléments explorés au TV (gynéco)",
      a:"Vagin et culs-de-sac ; en avant vessie et utérus ; latéralement tissu para-vaginal et releveurs ; en haut paramètres et annexes (ovaires) ; en arrière cul-de-sac de Douglas et ligaments utéro-sacrés." },
    { id:"g13", cat:"gyn", diff:1, q:"Éléments à rechercher au TV (examen gynécologique)",
      a:"Vessie/point urétéral inférieur, vagin, utérus (col, corps), annexes, ligaments utéro-sacrés." },

    /* ---------------- SANTÉ PUBLIQUE / SONU ---------------- */
    { id:"s1", cat:"sp", diff:2, q:"Fonctions SONU de base",
      a:"• ATB injectables\n• Ocytociques injectables\n• Anticonvulsivants injectables\n• Extraction manuelle du placenta (DA)\n• Révision utérine\n• AVB assistée (ventouse/forceps)\n• Réanimation du nouveau-né", mnemo:"7 fonctions de base" },
    { id:"s2", cat:"sp", diff:2, q:"Fonctions SONU complet",
      a:"Les 7 fonctions de base + 2 :\n• Transfusion sanguine\n• Chirurgie obstétricale (césarienne, laparotomie GEU, rupture utérine, péritonite)", mnemo:"SONU base + Transfusion + Chirurgie" },
    { id:"s3", cat:"sp", diff:2, q:"Le concept des 3 retards",
      a:"• 1ᵉʳ : retard dans la reconnaissance du problème / décision de chercher des soins (communauté)\n• 2ᵉ : retard pour arriver au centre de santé (transfert)\n• 3ᵉ : retard dans l'obtention de soins de qualité au centre" },
    { id:"s4", cat:"sp", diff:1, q:"Facteurs du 1ᵉʳ retard",
      a:"• Facteurs socio-culturels (croyances, religion)\n• Manque de connaissance des signes de danger\n• Facteurs socio-économiques (atténués par la gratuité des soins)" },
    { id:"s5", cat:"sp", diff:2, q:"Causes directes et indirectes de la mortalité maternelle",
      a:"• Directes : hémorragie du PP (1ᵉʳ), HRP, rupture utérine, GEU, infections (2ᵉ), syndromes vasculo-rénaux (3ᵉ), avortements, accidents thromboemboliques\n• Indirectes : diabète, drépanocytose, cardiopathie, accidents d'anesthésie, anémie chronique, malnutrition, paludisme, SIDA" },
    { id:"s6", cat:"sp", diff:2, q:"Programme des CPN (calendrier)",
      a:"• 1ʳᵉ CPN : 12-16 semaines\n• 2ᵉ CPN : 20-24 semaines\n• 3ᵉ CPN : 28-32 semaines\n• 4ᵉ CPN : 36 semaines" },
    { id:"s7", cat:"sp", diff:1, q:"Composantes des CPN",
      a:"• Dépistage/PEC des maladies préexistantes et complications\n• Prévention des complications et maladies\n• Promotion de la santé\n• Préparation à l'accouchement et aux complications", mnemo:"4 P : Prévention, PEC, Promotion, Préparation" },
    { id:"s8", cat:"sp", diff:2, q:"4 examens paracliniques obligatoires chez la femme enceinte",
      a:"GS/Rh (RAI si Rh-), électrophorèse de l'Hb, taux d'Hb/hémogramme, sérologie syphilis, albuminurie, glycosurie.\nComplémentaire : échographie (datation T1, morphologie T2, biométrie T3)." },
    { id:"s9", cat:"sp", diff:1, q:"3 signes cliniques de la MFIU",
      a:"• Absence de mouvements fœtaux\n• Disparition des BDCF (Pinard ou ERCF)\n• RCIU (HU plus petite que l'âge gestationnel)" },
    { id:"s10", cat:"sp", diff:2, q:"Causes de MFIU",
      a:"• Maternelles : prééclampsie, HTA, cardiopathie, diabète, anémie sévère, hémoglobinopathies, âge avancé, incompatibilité Rh, lupus, traumatisme\n• Ovulaires : grossesses multiples, malformations, anomalies génétiques, grossesse prolongée, PP/HRP, RPM + infection" },
    { id:"s11", cat:"sp", diff:1, q:"Mesures préventives de l'anémie durant la grossesse",
      a:"• Alimentation riche et variée (viande, foie, baobab, soumbala…)\n• Fer 60 mg/j + acide folique 400 µg/j + vitamine C\n• Chimioprophylaxie antipaludique (SP) + MILDA\n• Déparasitage (albendazole 400 mg dose unique)" },

    /* ---------------- TERRAINS PARTICULIERS ---------------- */
    { id:"t1", cat:"terr", diff:3, q:"CAT devant une crise vaso-occlusive (drépano) à 34 SA",
      a:"Médical : hospitalisation, VVP G18, O2 6 L, réchauffer.\nAntalgie : EVA ≥ 7 → morphine 6 mg bolus puis titration + paracétamol 1 g/6h ; EVA 3-7 → paracétamol + néfopam ± tramadol.\nRéhydrater (RL/SSI 1 L en 1h puis 3 L/24h). Transfuser si Hb < 8 (objectif 9-11).\nObstétrical : tocolyse si MAP (éviter le salbutamol).", mnemo:"HAATOP : Hydratation, Analgésie, Anti-inflammatoire, Transfusion, Oxygène, Psychothérapie" },
    { id:"t2", cat:"terr", diff:2, q:"Traitement de la crise drépanocytaire",
      a:"H : Hydratation\nA : Analgésie\nA : Anti-inflammatoire\nT : Transfusion\nO : Oxygène\nP : Psychothérapie", mnemo:"HAATOP" },
    { id:"t3", cat:"terr", diff:2, q:"Complications de la drépanocytose et grossesse",
      a:"• Choc cardiogénique\n• Choc septique\n• Embolie amniotique\n• Embolie graisseuse\n• HELLP syndrome\n• Stéatose hépatique aiguë gravidique (SHAG)" },
    { id:"t4", cat:"terr", diff:2, q:"Influence de l'anémie sur la grossesse",
      a:"• Grossesse : avortement, accouchement prématuré, RCIU, souffrance fœtale chronique, MFIU\n• Travail : dystocie dynamique (retard de dilatation), dystocie d'expulsion\n• Suites de couches : endométrite, phlébites, retard de cicatrisation" },
    { id:"t5", cat:"terr", diff:2, q:"Éléments du diagnostic du diabète gestationnel",
      a:"• Clinique : ATCD obstétricaux (macrosomie, mort-né, hydramnios, HTA), ATCD familiaux (diabète/obésité), anomalies actuelles (hydramnios, infections récidivantes)\n• Bio : glycémie postprandiale > 1,40 g/l ; pathologique si glycémie > 5,8 mmol/l à jeun, > 7,8 après charge\n• Confirmation : HGPO dès la 24ᵉ SA" },
    { id:"t6", cat:"terr", diff:2, q:"Complications du diabète gestationnel",
      a:"• Grossesse : hydramnios + macrosomie, HTA, accouchement prématuré, infections urinaires\n• Néonatales : détresse respiratoire (retard de surfactant), cardiomyopathie, hypocalcémie, hypoglycémie, polyglobulie, ictère, risque de devenir diabétique (1-5%)" },
    { id:"t7", cat:"terr", diff:2, q:"Phases du vomissement gravidique grave + traitement",
      a:"2 phases : phase émétisante, phase de dénutrition.\nTRT : rééquilibration hydro-électrolytique, antiémétiques, neurotropes, pansements gastriques, hépatoprotecteurs, boissons fraîches abondantes non gazeuses." },
    { id:"t8", cat:"terr", diff:2, q:"3 tableaux cliniques de l'IU pendant la grossesse + complications",
      a:"Tableaux : bactériurie asymptomatique, cystite aiguë, pyélonéphrite aiguë.\n• Complications maternelles : septicémie, PNA gravido-toxique, néphrite interstitielle, ↑risque de toxémie\n• Fœtales : accouchement prématuré, mort périnatale, infection néonatale, hypotrophie" },
    { id:"t9", cat:"terr", diff:2, q:"Facteurs favorisants et complications des grossesses multiples",
      a:"Facteurs : multiparité, âge avancé, hérédité, race, nutrition, inducteurs.\nComplications : maternelles (vomissements graves, toxémie, anémie ferriprive), fœtales (souffrance fœtale, anoxie, accrochage des pôles, enroulement des cordons)." },

    /* ---------------- DÉCHIRURES & TRAUMA (rattaché acc) ---------------- */
    { id:"a17", cat:"acc", diff:2, q:"Classification des déchirures du périnée",
      a:"• Incomplètes (sans atteinte du sphincter anal) : 1ᵉʳ° commissure, 2ᵉ° partie ant. du noyau fibreux, 3ᵉ° tous les muscles du noyau fibreux\n• Complète : rupture du sphincter anal (cloaque vulve-anus)\n• Complète et compliquée : + atteinte de la muqueuse anale\n• Centrale : au centre du périnée" },
    { id:"a18", cat:"acc", diff:1, q:"Facteurs des déchirures du périnée",
      a:"• Maternels : primiparité, périnée court, excision\n• Fœtaux : macrosomie, dégagement occipito-sacré, accouchement trop rapide\n• Iatrogènes : mauvaise application forceps/ventouse, grande extraction du siège, dystocie des épaules" },
    { id:"a19", cat:"acc", diff:1, q:"6 complications traumatiques de l'accouchement",
      a:"Lésions du périnée, du vagin, vulvaires, du col, du corps utérin, du rectum, de l'urètre.\n(Aussi : déchirures, incontinence urinaire, fistule vésico-vaginale/vésico-utérine.)" },
    { id:"a20", cat:"acc", diff:2, q:"Signes cliniques de la fistule vésico-vaginale obstétricale",
      a:"• Immédiat : urines hématiques, passage de la sonde dans le vagin\n• Tardif : pertes liquidiennes continues par le vagin, odeur ammoniacale\nDiagnostic : examen sous valves/spéculum ; en cas de doute, épreuve au bleu de méthylène." },
    { id:"a21", cat:"acc", diff:1, q:"CAT devant une circulaire du cordon à la phase expulsive",
      a:"• Circulaire lâche : faire glisser par-dessus la tête\n• Peu lâche : faire glisser sous l'épaule antérieure\n• Serré ou plusieurs boucles : clamper avec 2 pinces à 3 cm, sectionner entre les deux, dérouler, finir l'accouchement, réanimer si besoin." }
  ]
};
